name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Posts service
      - run: npm install
        working-directory: ./simple-microservices-main/posts
      - run: npm test
        working-directory: ./simple-microservices-main/posts

      # Comments service
      - run: npm install
        working-directory: ./simple-microservices-main/comments
      - run: npm test
        working-directory: ./simple-microservices-main/comments

      # Query service
      - run: npm install
        working-directory: ./simple-microservices-main/query
      - run: npm test
        working-directory: ./simple-microservices-main/query

      # Moderation service
      - run: npm install
        working-directory: ./simple-microservices-main/moderation
      - run: npm test
        working-directory: ./simple-microservices-main/moderation

      # Client
      - run: npm install
        working-directory: ./simple-microservices-main/client
      - run: npm test
        working-directory: ./simple-microservices-main/client
